name: Hello World Workflow

# Trigger on every push to any branch
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"

      - name: List files
        run: ls -la
